#!/bin/bash -ae

if [ ! -z "$UPSTARTSERVICE" ]; then
    echo "Stop service by upstart"
    sudo initctl stop $UPSTARTSERVICE
else
    echo "Stop service without upstart"
    abspath=$(cd ${0%/*} && echo $PWD/${0##*/})
    scripts_dir=`dirname "$abspath"`
    echo "scripts_dir $scripts_dir"
    $scripts_dir/../../container_runtime/bin/catalina.sh stop
fi

echo "Done shutdown"
