package com.ebay.cloud.cms.model.raptor_paas;



import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Branch extends GenericCMSEntity {


	public Branch() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public Boolean getIsMain(){
		return (Boolean)getFieldValue("isMain");
	}

	public void setIsMain(Boolean attrVal_isMain){
		setFieldValue("isMain", attrVal_isMain);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Branch";
	}
	
}