package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Cluster extends GenericCMSEntity {


	public Cluster() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public String getAppId(){
		return (String)getFieldValue("appId");
	}

	public void setAppId(String attrVal_appId){
		setFieldValue("appId", attrVal_appId);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public List<Compute> getComputes(){
		return (List<Compute>) getFieldValue("computes");
	}

	public void setComputes(List<Compute> attrVals_computes){
		setFieldValue("computes", attrVals_computes);
	}
	
	public void addComputes(Compute attrVal_computes){
		addFieldValue("computes", attrVal_computes);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}
		
	public List<UpdateStrategy> getUpdateStrategies(){
		return (List<UpdateStrategy>) getFieldValue("updateStrategies");
	}

	public void setUpdateStrategies(List<UpdateStrategy> attrVals_updateStrategies){
		setFieldValue("updateStrategies", attrVals_updateStrategies);
	}
	
	public void addUpdateStrategies(UpdateStrategy attrVal_updateStrategies){
		addFieldValue("updateStrategies", attrVal_updateStrategies);
	}
		
	public List<String> getActiveManifestRef(){
		return (List<String>)getFieldValue("activeManifestRef");
	}

	public void setActiveManifestRef(List<String> attrVals_activeManifestRef){
		setFieldValue("activeManifestRef", attrVals_activeManifestRef);
	}

	public void addActiveManifestRef(String attrVal_activeManifestRef){
		addFieldValue("activeManifestRef", attrVal_activeManifestRef);
	}

	public Boolean getActiveManifestDiff(){
		return (Boolean)getFieldValue("activeManifestDiff");
	}

	public void setActiveManifestDiff(Boolean attrVal_activeManifestDiff){
		setFieldValue("activeManifestDiff", attrVal_activeManifestDiff);
	}
		
	public List<String> getManifestRef(){
		return (List<String>)getFieldValue("manifestRef");
	}

	public void setManifestRef(List<String> attrVals_manifestRef){
		setFieldValue("manifestRef", attrVals_manifestRef);
	}

	public void addManifestRef(String attrVal_manifestRef){
		addFieldValue("manifestRef", attrVal_manifestRef);
	}

	public String getActiveManifestCur(){
		return (String)getFieldValue("activeManifestCur");
	}

	public void setActiveManifestCur(String attrVal_activeManifestCur){
		setFieldValue("activeManifestCur", attrVal_activeManifestCur);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Cluster";
	}
	
}