package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Company extends GenericCMSEntity {


	public Company() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public List<Department> getDepartment(){
		return (List<Department>) getFieldValue("department");
	}

	public void setDepartment(List<Department> attrVals_department){
		setFieldValue("department", attrVals_department);
	}
	
	public void addDepartment(Department attrVal_department){
		addFieldValue("department", attrVal_department);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Company";
	}
	
}