package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Compute extends GenericCMSEntity {


	public Compute() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public Boolean getHttps(){
		return (Boolean)getFieldValue("https");
	}

	public void setHttps(Boolean attrVal_https){
		setFieldValue("https", attrVal_https);
	}

	public Boolean getManifestDiff(){
		return (Boolean)getFieldValue("manifestDiff");
	}

	public void setManifestDiff(Boolean attrVal_manifestDiff){
		setFieldValue("manifestDiff", attrVal_manifestDiff);
	}

	public String getLocation(){
		return (String)getFieldValue("location");
	}

	public void setLocation(String attrVal_location){
		setFieldValue("location", attrVal_location);
	}

	public String getAdminStatus(){
		return (String)getFieldValue("adminStatus");
	}

	public void setAdminStatus(String attrVal_adminStatus){
		setFieldValue("adminStatus", attrVal_adminStatus);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}

	public String getComputeState(){
		return (String)getFieldValue("computeState");
	}

	public void setComputeState(String attrVal_computeState){
		setFieldValue("computeState", attrVal_computeState);
	}
		
	public List<String> getActiveManifestRef(){
		return (List<String>)getFieldValue("activeManifestRef");
	}

	public void setActiveManifestRef(List<String> attrVals_activeManifestRef){
		setFieldValue("activeManifestRef", attrVals_activeManifestRef);
	}

	public void addActiveManifestRef(String attrVal_activeManifestRef){
		addFieldValue("activeManifestRef", attrVal_activeManifestRef);
	}

	public String getFqdn(){
		return (String)getFieldValue("fqdn");
	}

	public void setFqdn(String attrVal_fqdn){
		setFieldValue("fqdn", attrVal_fqdn);
	}

	public String getActiveManifestCur(){
		return (String)getFieldValue("activeManifestCur");
	}

	public void setActiveManifestCur(String attrVal_activeManifestCur){
		setFieldValue("activeManifestCur", attrVal_activeManifestCur);
	}

	public String getAssetStatus(){
		return (String)getFieldValue("assetStatus");
	}

	public void setAssetStatus(String attrVal_assetStatus){
		setFieldValue("assetStatus", attrVal_assetStatus);
	}
		
	public List<String> getManifestRef(){
		return (List<String>)getFieldValue("manifestRef");
	}

	public void setManifestRef(List<String> attrVals_manifestRef){
		setFieldValue("manifestRef", attrVals_manifestRef);
	}

	public void addManifestRef(String attrVal_manifestRef){
		addFieldValue("manifestRef", attrVal_manifestRef);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getManifestCur(){
		return (String)getFieldValue("manifestCur");
	}

	public void setManifestCur(String attrVal_manifestCur){
		setFieldValue("manifestCur", attrVal_manifestCur);
	}

	public Boolean getActiveManifestDiff(){
		return (Boolean)getFieldValue("activeManifestDiff");
	}

	public void setActiveManifestDiff(Boolean attrVal_activeManifestDiff){
		setFieldValue("activeManifestDiff", attrVal_activeManifestDiff);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Compute";
	}
	
}