package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Department extends GenericCMSEntity {


	public Department() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public List<Squad> getSquad(){
		return (List<Squad>) getFieldValue("squad");
	}

	public void setSquad(List<Squad> attrVals_squad){
		setFieldValue("squad", attrVals_squad);
	}
	
	public void addSquad(Squad attrVal_squad){
		addFieldValue("squad", attrVal_squad);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}
		
	public List<Team> getTeam(){
		return (List<Team>) getFieldValue("team");
	}

	public void setTeam(List<Team> attrVals_team){
		setFieldValue("team", attrVals_team);
	}
	
	public void addTeam(Team attrVal_team){
		addFieldValue("team", attrVal_team);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Department";
	}
	
}