package com.ebay.cloud.cms.model.raptor_paas;



import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class ExpressionTest extends GenericCMSEntity {


	public ExpressionTest() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public Double getD1(){
		return (Double)getFieldValue("d1");
	}

	public void setD1(Double attrVal_d1){
		setFieldValue("d1", attrVal_d1);
	}

	public Double getD(){
		return (Double)getFieldValue("d");
	}

	public void setD(Double attrVal_d){
		setFieldValue("d", attrVal_d);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public Integer getEi(){
		return (Integer)getFieldValue("ei");
	}

	public void setEi(Integer attrVal_ei){
		setFieldValue("ei", attrVal_ei);
	}

	public String getEname(){
		return (String)getFieldValue("ename");
	}

	public void setEname(String attrVal_ename){
		setFieldValue("ename", attrVal_ename);
	}

	public String getName1(){
		return (String)getFieldValue("name1");
	}

	public void setName1(String attrVal_name1){
		setFieldValue("name1", attrVal_name1);
	}

	public Integer getI1(){
		return (Integer)getFieldValue("i1");
	}

	public void setI1(Integer attrVal_i1){
		setFieldValue("i1", attrVal_i1);
	}

	public Double getEd(){
		return (Double)getFieldValue("ed");
	}

	public void setEd(Double attrVal_ed){
		setFieldValue("ed", attrVal_ed);
	}

	public Integer getI(){
		return (Integer)getFieldValue("i");
	}

	public void setI(Integer attrVal_i){
		setFieldValue("i", attrVal_i);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "ExpressionTest";
	}
	
}