package com.ebay.cloud.cms.model.raptor_paas;

import org.codehaus.jackson.JsonNode;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class History extends GenericCMSEntity {


	public History() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public JsonNode getLogBody(){
		return (JsonNode)getFieldValue("logBody");
	}

	public void setLogBody(JsonNode attrVal_logBody){
		setFieldValue("logBody", attrVal_logBody);
	}

	public String getSourceIp(){
		return (String)getFieldValue("sourceIp");
	}

	public void setSourceIp(String attrVal_sourceIp){
		setFieldValue("sourceIp", attrVal_sourceIp);
	}

	public String getEntityId(){
		return (String)getFieldValue("entityId");
	}

	public void setEntityId(String attrVal_entityId){
		setFieldValue("entityId", attrVal_entityId);
	}

	public String getOperType(){
		return (String)getFieldValue("operType");
	}

	public void setOperType(String attrVal_operType){
		setFieldValue("operType", attrVal_operType);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "History";
	}
	
}