package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class LOJCompute extends GenericCMSEntity {


	public LOJCompute() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public List<LOJServiceInstance> getSvcInstances(){
		return (List<LOJServiceInstance>) getFieldValue("svcInstances");
	}

	public void setSvcInstances(List<LOJServiceInstance> attrVals_svcInstances){
		setFieldValue("svcInstances", attrVals_svcInstances);
	}
	
	public void addSvcInstances(LOJServiceInstance attrVal_svcInstances){
		addFieldValue("svcInstances", attrVal_svcInstances);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public LOJServiceInstance getSvcInstance(){
		return (LOJServiceInstance)getFieldValue("svcInstance");
	}

	public void setSvcInstance(LOJServiceInstance attrVal_svcInstance){
		setFieldValue("svcInstance", attrVal_svcInstance);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "LOJCompute";
	}
	
}