package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class LOJDataService extends GenericCMSEntity {


	public LOJDataService() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public LOJApplicationService getApplicationService(){
		return (LOJApplicationService)getFieldValue("applicationService");
	}

	public void setApplicationService(LOJApplicationService attrVal_applicationService){
		setFieldValue("applicationService", attrVal_applicationService);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}
		
	public List<LOJApplicationService> getApplicationServices(){
		return (List<LOJApplicationService>) getFieldValue("applicationServices");
	}

	public void setApplicationServices(List<LOJApplicationService> attrVals_applicationServices){
		setFieldValue("applicationServices", attrVals_applicationServices);
	}
	
	public void addApplicationServices(LOJApplicationService attrVal_applicationServices){
		addFieldValue("applicationServices", attrVal_applicationServices);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "LOJDataService";
	}
	
}