package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class LOJServiceInstance extends GenericCMSEntity {


	public LOJServiceInstance() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public LOJApplicationService getAppService(){
		return (LOJApplicationService)getFieldValue("appService");
	}

	public void setAppService(LOJApplicationService attrVal_appService){
		setFieldValue("appService", attrVal_appService);
	}
		
	public List<LOJApplicationService> getAppServices(){
		return (List<LOJApplicationService>) getFieldValue("appServices");
	}

	public void setAppServices(List<LOJApplicationService> attrVals_appServices){
		setFieldValue("appServices", attrVals_appServices);
	}
	
	public void addAppServices(LOJApplicationService attrVal_appServices){
		addFieldValue("appServices", attrVal_appServices);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public LOJCompute getRunsOn(){
		return (LOJCompute)getFieldValue("runsOn");
	}

	public void setRunsOn(LOJCompute attrVal_runsOn){
		setFieldValue("runsOn", attrVal_runsOn);
	}
		
	public List<LOJCompute> getRunsOns(){
		return (List<LOJCompute>) getFieldValue("runsOns");
	}

	public void setRunsOns(List<LOJCompute> attrVals_runsOns){
		setFieldValue("runsOns", attrVals_runsOns);
	}
	
	public void addRunsOns(LOJCompute attrVal_runsOns){
		addFieldValue("runsOns", attrVal_runsOns);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "LOJServiceInstance";
	}
	
}