package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Room extends GenericCMSEntity {


	public Room() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	
		
	public List<String> getLevel(){
		return (List<String>)getFieldValue("level");
	}

	public void setLevel(List<String> attrVals_level){
		setFieldValue("level", attrVals_level);
	}

	public void addLevel(String attrVal_level){
		addFieldValue("level", attrVal_level);
	}

	public String getFloor(){
		return (String)getFieldValue("floor");
	}

	public void setFloor(String attrVal_floor){
		setFieldValue("floor", attrVal_floor);
	}
		
	public List<String> getWindow(){
		return (List<String>)getFieldValue("window");
	}

	public void setWindow(List<String> attrVals_window){
		setFieldValue("window", attrVals_window);
	}

	public void addWindow(String attrVal_window){
		addFieldValue("window", attrVal_window);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public List<Door> getPath(){
		return (List<Door>) getFieldValue("path");
	}

	public void setPath(List<Door> attrVals_path){
		setFieldValue("path", attrVals_path);
	}
	
	public void addPath(Door attrVal_path){
		addFieldValue("path", attrVal_path);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Room";
	}
	
}