package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;
import org.codehaus.jackson.JsonNode;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class ServiceInstance extends GenericCMSEntity {


	public ServiceInstance() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public String getPort(){
		return (String)getFieldValue("port");
	}

	public void setPort(String attrVal_port){
		setFieldValue("port", attrVal_port);
	}

	public Boolean getHttps(){
		return (Boolean)getFieldValue("https");
	}

	public void setHttps(Boolean attrVal_https){
		setFieldValue("https", attrVal_https);
	}

	public Boolean getManifestDiff(){
		return (Boolean)getFieldValue("manifestDiff");
	}

	public void setManifestDiff(Boolean attrVal_manifestDiff){
		setFieldValue("manifestDiff", attrVal_manifestDiff);
	}

	public String getHealthStatus(){
		return (String)getFieldValue("healthStatus");
	}

	public void setHealthStatus(String attrVal_healthStatus){
		setFieldValue("healthStatus", attrVal_healthStatus);
	}
		
	public Compute getRunsOn(){
		return (Compute)getFieldValue("runsOn");
	}

	public void setRunsOn(Compute attrVal_runsOn){
		setFieldValue("runsOn", attrVal_runsOn);
	}

	public JsonNode getProperties(){
		return (JsonNode)getFieldValue("properties");
	}

	public void setProperties(JsonNode attrVal_properties){
		setFieldValue("properties", attrVal_properties);
	}
		
	public List<String> getActiveManifestRef(){
		return (List<String>)getFieldValue("activeManifestRef");
	}

	public void setActiveManifestRef(List<String> attrVals_activeManifestRef){
		setFieldValue("activeManifestRef", attrVals_activeManifestRef);
	}

	public void addActiveManifestRef(String attrVal_activeManifestRef){
		addFieldValue("activeManifestRef", attrVal_activeManifestRef);
	}

	public String getActiveManifestCur(){
		return (String)getFieldValue("activeManifestCur");
	}

	public void setActiveManifestCur(String attrVal_activeManifestCur){
		setFieldValue("activeManifestCur", attrVal_activeManifestCur);
	}
		
	public List<String> getManifestRef(){
		return (List<String>)getFieldValue("manifestRef");
	}

	public void setManifestRef(List<String> attrVals_manifestRef){
		setFieldValue("manifestRef", attrVals_manifestRef);
	}

	public void addManifestRef(String attrVal_manifestRef){
		addFieldValue("manifestRef", attrVal_manifestRef);
	}
		
	public ApplicationService getAppService(){
		return (ApplicationService)getFieldValue("appService");
	}

	public void setAppService(ApplicationService attrVal_appService){
		setFieldValue("appService", attrVal_appService);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getManifestCur(){
		return (String)getFieldValue("manifestCur");
	}

	public void setManifestCur(String attrVal_manifestCur){
		setFieldValue("manifestCur", attrVal_manifestCur);
	}

	public Boolean getActiveManifestDiff(){
		return (Boolean)getFieldValue("activeManifestDiff");
	}

	public void setActiveManifestDiff(Boolean attrVal_activeManifestDiff){
		setFieldValue("activeManifestDiff", attrVal_activeManifestDiff);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "ServiceInstance";
	}
	
}