package com.ebay.cloud.cms.model.raptor_paas;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Team extends GenericCMSEntity {


	public Team() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public Boolean getIsLargeTeam(){
		return (Boolean)getFieldValue("isLargeTeam");
	}

	public void setIsLargeTeam(Boolean attrVal_isLargeTeam){
		setFieldValue("isLargeTeam", attrVal_isLargeTeam);
	}
		
	public List<Person> getPerson(){
		return (List<Person>) getFieldValue("person");
	}

	public void setPerson(List<Person> attrVals_person){
		setFieldValue("person", attrVals_person);
	}
	
	public void addPerson(Person attrVal_person){
		addFieldValue("person", attrVal_person);
	}
		
	public List<String> getSeat(){
		return (List<String>)getFieldValue("seat");
	}

	public void setSeat(List<String> attrVals_seat){
		setFieldValue("seat", attrVals_seat);
	}

	public void addSeat(String attrVal_seat){
		addFieldValue("seat", attrVal_seat);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getLabel(){
		return (String)getFieldValue("label");
	}

	public void setLabel(String attrVal_label){
		setFieldValue("label", attrVal_label);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Team";
	}
	
}