package com.ebay.cloud.cms.model.raptor_paas;

import java.util.Date;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class UpdateStrategy extends GenericCMSEntity {


	public UpdateStrategy() {
		set_type(get_metaclass());
//		set_repo("raptor-paas");
	}

	// the getter/setter method
	

	public Date getLastModifiedTime(){
		return (Date) getDateField("lastModifiedTime");
	}

	public void setLastModifiedTime(Date attrVal_lastModifiedTime){
		setDateField("lastModifiedTime", attrVal_lastModifiedTime);
	}

	public String getFailure(){
		return (String)getFieldValue("failure");
	}

	public void setFailure(String attrVal_failure){
		setFieldValue("failure", attrVal_failure);
	}

	public String getDescription(){
		return (String)getFieldValue("description");
	}

	public void setDescription(String attrVal_description){
		setFieldValue("description", attrVal_description);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getStrategy(){
		return (String)getFieldValue("strategy");
	}

	public void setStrategy(String attrVal_strategy){
		setFieldValue("strategy", attrVal_strategy);
	}

	public String getType(){
		return (String)getFieldValue("type");
	}

	public void setType(String attrVal_type){
		setFieldValue("type", attrVal_type);
	}

	public String getGroups(){
		return (String)getFieldValue("groups");
	}

	public void setGroups(String attrVal_groups){
		setFieldValue("groups", attrVal_groups);
	}

	public String getThreshold(){
		return (String)getFieldValue("threshold");
	}

	public void setThreshold(String attrVal_threshold){
		setFieldValue("threshold", attrVal_threshold);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "UpdateStrategy";
	}
	
}