package com.ebay.cloud.cms.model.software_deployment;

import java.util.Date;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class Approval extends GenericCMSEntity {


	public Approval() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public String getAppId(){
		return (String)getFieldValue("appId");
	}

	public void setAppId(String attrVal_appId){
		setFieldValue("appId", attrVal_appId);
	}

	public String getManifestCreatedBy(){
		return (String)getFieldValue("manifestCreatedBy");
	}

	public void setManifestCreatedBy(String attrVal_manifestCreatedBy){
		setFieldValue("manifestCreatedBy", attrVal_manifestCreatedBy);
	}

	public String getCreatedBy(){
		return (String)getFieldValue("createdBy");
	}

	public void setCreatedBy(String attrVal_createdBy){
		setFieldValue("createdBy", attrVal_createdBy);
	}

	public Date getManifestCreatedTime(){
		return (Date) getDateField("manifestCreatedTime");
	}

	public void setManifestCreatedTime(Date attrVal_manifestCreatedTime){
		setDateField("manifestCreatedTime", attrVal_manifestCreatedTime);
	}

	public Date getCreatedTime(){
		return (Date) getDateField("createdTime");
	}

	public void setCreatedTime(Date attrVal_createdTime){
		setDateField("createdTime", attrVal_createdTime);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public DeployClassOfService getClassOfService(){
		return (DeployClassOfService)getFieldValue("classOfService");
	}

	public void setClassOfService(DeployClassOfService attrVal_classOfService){
		setFieldValue("classOfService", attrVal_classOfService);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "Approval";
	}
	
}