package com.ebay.cloud.cms.model.software_deployment;



import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class DeploymentTarget extends GenericCMSEntity {


	public DeploymentTarget() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public String getTargetNode(){
		return (String)getFieldValue("targetNode");
	}

	public void setTargetNode(String attrVal_targetNode){
		setFieldValue("targetNode", attrVal_targetNode);
	}

	public Boolean getInOrder(){
		return (Boolean)getFieldValue("inOrder");
	}

	public void setInOrder(Boolean attrVal_inOrder){
		setFieldValue("inOrder", attrVal_inOrder);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public Manifest getManifest(){
		return (Manifest)getFieldValue("manifest");
	}

	public void setManifest(Manifest attrVal_manifest){
		setFieldValue("manifest", attrVal_manifest);
	}
		
	public ManifestVersion getManifestVersion(){
		return (ManifestVersion)getFieldValue("manifestVersion");
	}

	public void setManifestVersion(ManifestVersion attrVal_manifestVersion){
		setFieldValue("manifestVersion", attrVal_manifestVersion);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "DeploymentTarget";
	}
	
}