package com.ebay.cloud.cms.model.software_deployment;

import java.util.Date;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class DeploymentEvent extends GenericCMSEntity {


	public DeploymentEvent() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public Date getLastModifiedTime(){
		return (Date) getDateField("lastModifiedTime");
	}

	public void setLastModifiedTime(Date attrVal_lastModifiedTime){
		setDateField("lastModifiedTime", attrVal_lastModifiedTime);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "DeploymentEvent";
	}
	
}