package com.ebay.cloud.cms.model.software_deployment;

import java.util.List;
import java.util.ArrayList;
import java.util.Date;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class ManifestVersion extends GenericCMSEntity {


	public ManifestVersion() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	
		
	public List<Approval> getApprovals(){
		return (List<Approval>) getFieldValue("approvals");
	}

	public void setApprovals(List<Approval> attrVals_approvals){
		setFieldValue("approvals", attrVals_approvals);
	}
	
	public void addApprovals(Approval attrVal_approvals){
		addFieldValue("approvals", attrVal_approvals);
	}
		
	public List<Package> getPackages(){
		return (List<Package>) getFieldValue("packages");
	}

	public void setPackages(List<Package> attrVals_packages){
		setFieldValue("packages", attrVals_packages);
	}
	
	public void addPackages(Package attrVal_packages){
		addFieldValue("packages", attrVal_packages);
	}

	public String getCreatedBy(){
		return (String)getFieldValue("createdBy");
	}

	public void setCreatedBy(String attrVal_createdBy){
		setFieldValue("createdBy", attrVal_createdBy);
	}

	public Date getCreatedTime(){
		return (Date) getDateField("createdTime");
	}

	public void setCreatedTime(Date attrVal_createdTime){
		setDateField("createdTime", attrVal_createdTime);
	}

	public String getDescription(){
		return (String)getFieldValue("description");
	}

	public void setDescription(String attrVal_description){
		setFieldValue("description", attrVal_description);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "ManifestVersion";
	}
	
}