package com.ebay.cloud.cms.model.software_deployment;

import java.util.List;
import java.util.ArrayList;
import org.codehaus.jackson.JsonNode;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class NoUse extends GenericCMSEntity {


	public NoUse() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public JsonNode getNoUseProperties(){
		return (JsonNode)getFieldValue("noUseProperties");
	}

	public void setNoUseProperties(JsonNode attrVal_noUseProperties){
		setFieldValue("noUseProperties", attrVal_noUseProperties);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public List<String> getNoUseHistory(){
		return (List<String>)getFieldValue("noUseHistory");
	}

	public void setNoUseHistory(List<String> attrVals_noUseHistory){
		setFieldValue("noUseHistory", attrVals_noUseHistory);
	}

	public void addNoUseHistory(String attrVal_noUseHistory){
		addFieldValue("noUseHistory", attrVal_noUseHistory);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "NoUse";
	}
	
}