package com.ebay.cloud.cms.model.software_deployment;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class PoolCluster extends GenericCMSEntity {


	public PoolCluster() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}

	public String getUsage(){
		return (String)getFieldValue("usage");
	}

	public void setUsage(String attrVal_usage){
		setFieldValue("usage", attrVal_usage);
	}
		
	public List<GenericCMSEntity> getPools(){
		return (List<GenericCMSEntity>) getFieldValue("pools");
	}

	public void setPools(List<GenericCMSEntity> attrVals_pools){
		setFieldValue("pools", attrVals_pools);
	}
	
	public void addPools(GenericCMSEntity attrVal_pools){
		addFieldValue("pools", attrVal_pools);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "PoolCluster";
	}
	
}