package com.ebay.cloud.cms.model.software_deployment;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class RefApplicationService extends GenericCMSEntity {


	public RefApplicationService() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	
		
	public List<GenericCMSEntity> getServices(){
		return (List<GenericCMSEntity>) getFieldValue("services");
	}

	public void setServices(List<GenericCMSEntity> attrVals_services){
		setFieldValue("services", attrVals_services);
	}
	
	public void addServices(GenericCMSEntity attrVal_services){
		addFieldValue("services", attrVal_services);
	}

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public List<Manifest> getManifest(){
		return (List<Manifest>) getFieldValue("manifest");
	}

	public void setManifest(List<Manifest> attrVals_manifest){
		setFieldValue("manifest", attrVals_manifest);
	}
	
	public void addManifest(Manifest attrVal_manifest){
		addFieldValue("manifest", attrVal_manifest);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "RefApplicationService";
	}
	
}