package com.ebay.cloud.cms.model.software_deployment;

import java.util.List;
import java.util.ArrayList;


import com.ebay.cloud.cms.typsafe.entity.GenericCMSEntity;

import org.codehaus.jackson.annotate.JsonIgnore;

/**
 * CMS generated entity.
 * This class is generated by CMS type-safe api model exporter, DON'T modify this class.
 * 
 */
public class ServiceCluster extends GenericCMSEntity {


	public ServiceCluster() {
		set_type(get_metaclass());
//		set_repo("software-deployment");
	}

	// the getter/setter method
	

	public String getName(){
		return (String)getFieldValue("name");
	}

	public void setName(String attrVal_name){
		setFieldValue("name", attrVal_name);
	}
		
	public List<PoolCluster> getPoolClusters(){
		return (List<PoolCluster>) getFieldValue("poolClusters");
	}

	public void setPoolClusters(List<PoolCluster> attrVals_poolClusters){
		setFieldValue("poolClusters", attrVals_poolClusters);
	}
	
	public void addPoolClusters(PoolCluster attrVal_poolClusters){
		addFieldValue("poolClusters", attrVal_poolClusters);
	}

	@JsonIgnore
	public String get_metaclass(){
		return "ServiceCluster";
	}
	
}